--- OTTERPREP DATABASE SCHEMA
--- CREATED BY LAWSON
--- DATE: 2026-01-02
--- VERSION: 1.0.0
--- DATABASE TYPE: POSTGRESQL
--- DATABASE NAME: otterprep

CREATE DATABASE otterprep;

CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_name ON users (name);

CREATE TABLE IF NOT EXISTS scores (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	score BIGINT NOT NULL,
	mode VARCHAR(255) NOT NULL,
	correct_answers BIGINT NOT NULL,
	incorrect_answers BIGINT NOT NULL,
	total_questions BIGINT NOT NULL,
	time_taken_seconds BIGINT NOT NULL,
	subject_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS subjects (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
	id SERIAL PRIMARY KEY,
	subject_id BIGINT NOT NULL,
	question VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_questions_subject_id ON questions (subject_id);

CREATE TABLE IF NOT EXISTS options (
	id SERIAL PRIMARY KEY,
	question_id BIGINT NOT NULL,
	option VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP.

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_options_question_id ON options (question_id);

CREATE TABLE IF NOT EXISTS answers (
	id SERIAL PRIMARY KEY,
	question_id BIGINT NOT NULL,
	answer VARCHAR(255) NOT NULL,
	is_correct BOOLEAN NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);
