--- OTTERPREP DATABASE SCHEMA
--- CREATED BY LAWSON
--- DATE: 2026-01-02
--- VERSION: 1.0.1
--- DATABASE TYPE: POSTGRESQL
--- DATABASE NAME: otterprep

-- CREATE DATABASE otterprep;  -- Run separately if needed

-- Users table
CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_name ON users (name);

-- User roles table
CREATE TABLE IF NOT EXISTS user_roles (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	role VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Subjects table (must be before scores and questions)
CREATE TABLE IF NOT EXISTS subjects (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Scores table
CREATE TABLE IF NOT EXISTS scores (
	id SERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	score BIGINT NOT NULL,
	mode VARCHAR(255) NOT NULL,
	correct_answers BIGINT NOT NULL,
	incorrect_answers BIGINT NOT NULL,
	total_questions BIGINT NOT NULL,
	time_taken_seconds BIGINT NOT NULL,
	subject_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- Questions table
CREATE TABLE IF NOT EXISTS questions (
	id SERIAL PRIMARY KEY,
	subject_id BIGINT NOT NULL,
	question TEXT NOT NULL,
	is_multiple_choice BOOLEAN DEFAULT TRUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE INDEX IF NOT EXISTS idx_questions_subject_id ON questions (subject_id);

-- Options table
CREATE TABLE IF NOT EXISTS options (
	id SERIAL PRIMARY KEY,
	question_id BIGINT NOT NULL,
	option TEXT NOT NULL,
	is_correct BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_options_question_id ON options (question_id);

-- Answers table (explanations for questions)
CREATE TABLE IF NOT EXISTS answers (
	id SERIAL PRIMARY KEY,
	question_id BIGINT NOT NULL,
	answer TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	-- FOREIGN KEY CONSTRAINTS
	FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_answers_question_id ON answers (question_id);

